# Generated by Django 3.2.5 on 2021-07-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_rename_imagem_photo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
    ]
